version: '3.8'
services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'employeeDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Asdrt325698dsa'
      MYSQL_ROOT_PASSWORD: 'Asdrt325698dsa'
    volumes:
      - db_data:/var/lib/mysql
      - ./initDB.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - seperate_network

networks:
  seperate_network:
    name: seperate_network
    driver: bridge


volumes:
  db_data:
